version: '3.8'
services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress_container_1
    ports:
      - "8081:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: wp_password
      WORDPRESS_DB_NAME: wp_database
    volumes:
      - ./wordpress:/var/www/html

  db:
    image: mysql:5.7
    container_name: mysql_container_1
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: wp_database
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_password
    volumes:
      - ./db_data:/var/lib/mysql
